language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-linangular' ]; then cd .. && eval "mv $currentfolder generator-linangular" && cd generator-linangular; fi

